// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloseTabsToRight
{
    static class Vsix
    {
        public const string Id = "ee6375e5-ed09-4fba-a897-895813190958";
        public const string Name = "Close Tabs To Right";
        public const string Description = @"Close document tabs to the right of the current document.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Bill Pratt";
        public const string Tags = "close, tab, tabs, to, right, document";
    }
}
